<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>eu.jbeernink.hypospray</groupId>
		<artifactId>eu.jbeernink.hypospray.arquillian</artifactId>
		<version>${revision}</version>
	</parent>

	<groupId>eu.jbeernink.hypospray.arquillian</groupId>
	<artifactId>eu.jbeernink.hypospray.arquillian.container</artifactId>
	<version>${revision}</version>

	<dependencies>
		<dependency>
			<groupId>jakarta.enterprise</groupId>
			<artifactId>jakarta.enterprise.cdi-api</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.jboss.arquillian.container</groupId>
			<artifactId>arquillian-container-spi</artifactId>
		</dependency>

		<dependency>
			<groupId>org.jboss.arquillian.core</groupId>
			<artifactId>arquillian-core-spi</artifactId>
		</dependency>

		<dependency>
			<groupId>org.jboss.arquillian.test</groupId>
			<artifactId>arquillian-test-spi</artifactId>
		</dependency>

		<dependency>
			<groupId>eu.jbeernink.hypospray</groupId>
			<artifactId>eu.jbeernink.hypospray.annotation</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>eu.jbeernink.hypospray.compile</groupId>
			<artifactId>eu.jbeernink.hypospray.compile.servicedescriptor</artifactId>
			<version>${project.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.jboss.arquillian.junit5</groupId>
			<artifactId>arquillian-junit5-container</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>eu.jbeernink.hypospray.compile</groupId>
							<artifactId>eu.jbeernink.hypospray.compile.servicedescriptor</artifactId>
							<version>${project.version}</version>
						</path>
					</annotationProcessorPaths>
					<annotationProcessors>
						<annotationProcessor>eu.jbeernink.hypospray.compile.servicedescriptor.ServiceDescriptorGenerator
						</annotationProcessor>
					</annotationProcessors>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>lite</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<dependencies>
				<dependency>
					<groupId>eu.jbeernink.hypospray</groupId>
					<artifactId>eu.jbeernink.hypospray.lite</artifactId>
					<version>${project.version}</version>
				</dependency>
			</dependencies>
		</profile>
	</profiles>
</project>